language: python
jobs:
  include:
    - name: "Python 3.8 on Xenial Linux"
      python: "3.8"
    - name: "Python 3.8-dev on Xenial Linux"
      python: "3.8-dev"
install:
  - pip3 install -e .[dev] || pip install -e .[dev]
  - pip3 install codecov coverage || pip install codecov coverage
script:
  - coverage run -m unittest
after_success:
  - codecov
