language: python
jobs:
  include:
    - name: "Python 3.8 on Xenial Linux"
      python: "3.8"
    - name: "Python 3.8-dev on Xenial Linux"
      python: "3.8-dev"
    - name: "Python nightly on Xenial Linux"
      python: "nightly"
    - name: "Python 3.8.0 on Windows"
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install -e .[dev] || pip install -e .[dev]
  - pip3 install codecov coverage || pip install codecov coverage
script:
  - coverage run -m unittest
after_success:
  - codecov
